# Header
menu:
  Home: /
  Archives: /archives
  Technology: /technology
  About: "https://tanyapowell.co.uk"

# Logo Image Source
logo_src: https://s3-eu-west-1.amazonaws.com/tanyapowell/6105146987_93f5537c01_m.jpg

# Theme Main Subtitle
# subtitle_main: "{ Software Engineer | Wannabe Chef | Occasional Photographer | Reality TV Enthuiast }"

# Theme Secondary subtitle
# susbtitle_secondary: "{ Software Engineer | Wannabe Chef | Occasional Photographer | Reality TV Enthuiast }"

# Footer About Section
about_footer: "{ Software Engineer | Gluten Free Chef | Pop Culture Vulture }"

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "http://th21.st.depositphotos.com/1327515/6332/v/950/depositphotos_63321231-stock-illustration-color-cub.jpg"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates: true

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  # disqus_shortname: klugjo
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-69471485-1

# Social Accounts
twitter_url: https://twitter.com/tanya_powell
# facebook_url: https://www.facebook.com/
# instagram_url: https://www.instagram.com/
github_url: https://github.com/tanyapowell
# googleplus_url: https://plus.google.com/
# behance_url: https://www.behance.net/
# fivehundredpx_url: https://500px.com/
email_url: mailto:hello@tanyapowell.co.uk
rss_url: atom.xml/rss2.xml

# Configuration for hexo-image-sizes
image_sizes:
  pattern: !!js/regexp /\.(gif|jpg|jpeg|png)$/i
  profiles:
    body:
      width: 500 // height will adjust to preserve aspect ratio
    thumbnail:
      width: 100 // Image will be cropped to a square
      height: 100
    huge:
      height: 1000
      allowEnlargement: true
  defaultProfile: body
